---
title: "Article 1"
author:
  - name: Kawtar Dahman
date:
categories:
  - Mental diseases
  - Schizophrenia
preview:
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```






## Vocabulary
| Words from the text | Synonym/ definition in English | French translation |
| :-----------------: | :----------------------------: | :----------------: |
|     recrutement     |          enrolement            |    recruitment     |
|      screening      |           detecting            |     dépistage      |
|    predominantly    |           principaly           |   principalement   |
|      ancestry       |            heritage            |     ascendance     |
|    symmetrically    |          identically           |   symétriquement   |
|    computational    |         calculational          |       calcul       |
|      replicate      |           reproduce            |     reproduire     |
|        fund         |            finance             |      financer      |

## Analysis table


|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | University of Queensland                        |
| Published in?                | 03-07-2019                                                       |
| General topic?               |  (summarize the topic in one or two sentences)                      |
| Procedure/what was examined? | (Give some details about the topic, i.e. methodology/material/etc.) |
| Conclusions/discovery?       |  (what did the researchers conclude? Did they find something?)      |
| Remaining questions?         | (check if there are still interrogations at the end of the article) |





