---
title: "My english activity log"
---

Week 1: Hello everyone, this week i started watching a TV show that i heard a lot of good reviews about. It's named "The good doctor", and it talks about an autistic surgeon named "Shaun Murphy", he has a savant syndrome. "Savant syndrome" is when a person has a condition in which he is significantly mentally disabled, with social and communication problems, but can still be labeled as a "genius" thanks to his outstanding skills in various fields, especially those who are related to memory. 
The other surgeons labels "Shaun Murphy" as a souless robot, because he can't tell jokes, can't know if they are joking with him, can't figure out if they are being sarcastic with him therefore takes everything seriously and at the first degree ! Not only that, but he also can't be compassionate with patients and only relies on his spatial skills and photographic memory.
And of course, i'm watching it in english, that way,the actors voices are not modified even if it's still a little bit hard to understand some english medical terms.
