---
title: "My english activity log"
author:
  - name: "Dahman Kawtar"
date: 10-15-2019
categories:
  - "My english activity log"
preview: 
output:
  distill::distill_article:
    self_contained: false
---


# Week 1 :
Hello everyone, this week i started watching a TV show that i heard a lot of good reviews about. It's named "The good doctor", and it talks about an autistic surgeon named "Shaun Murphy", he has a savant syndrome. "Savant syndrome" is when a person has a condition in which he is significantly mentally disabled, with social and communication problems, but can still be labeled as a "genius" thanks to his outstanding skills in various fields, especially those who are related to memory. 
The other surgeons labels "Shaun Murphy" as a souless robot, because he can't tell jokes, can't know if they are joking with him, can't figure out if they are being sarcastic with him therefore takes everything seriously and at the first degree ! Not only that, but he also can't be compassionate with patients and only relies on his spatial skills and photographic memory.
And of course, i'm watching it in english, that way,the actors voices are not modified even if it's still a little bit hard to understand some english medical terms.



# Week 2 : 
Hello everyone, for this week, i continued watching the series of "The good doctor" that i talked about in my activities for the last week. Adding to that, i watched some videos of the TED-Ed talks. These videos consists of a serie of influential videos where many specialists talk in a lot of fields: business, science, education, psychology...The one that interests me the most is the last category. I find that experts's talks in this category are really entertaining and educative. It helps to understand and try to see things from another perspective. Which aid to know that everyone has it's own way of seeing and exploring things, that way, everyone's opinion is understood and respected.



# Week 3 :
Hello everyone, in this week, i didn't have much time considering that i was preparing for my presentation. But while preparing for it, i watched/read many videos/articles in english that has a connection with the subject of my presentation, that is "cloning".
Here is one video of the many i watched :
<https://www.bbvaopenmind.com/en/multimedia/videos/obtaining-human-embryonic-stem-cells-thru-therapeutic-cloning/>



# Week 4 :
Hello everyone, this week i tried to read some english articles and documentations about psychotic disorders, i found them really well exlained and educative as well. Here is one of the documentations i read :
<https://www.queensu.ca/studentwellness/mental-health/about-mental-health/psychotic-disorders>
I hope you will like it as much as i did.



# Week 5 :
Hello everyone, i found a channel on youtube that talks about everything and anything related to biology. I founded that videos made by this channel are explicated in such an entertaining way that it makes the learning so easy ans enjoyeable. It's called "Biology crash course" .I hope you will like this channel as much as i did.
